apiVersion: v1
kind: Service
metadata:
  name: web-app-nodeport-service
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
